### ISSUE TITLE
Download data without bigquery?

### ISSUE THREAD

**Issue by robvanderg** [UniversalDependencies/UD_English-GUMReddit#1]
Would it be possible to download the data without making a bigquery account? The pip package seems to be updated (get_client does not exist anymore). Besides that,  it is non-trivial to get the key.json file.

**Comment by amir-zeldes** [comment]
Hi and thanks for reporting the issue - actually it should be possible to download even without that. There is a fallback using a proxy server, but it stopped working due to a server upgrade. I think it should be working now. Can you try again?

**Comment by robvanderg** [comment]
Hi, thanks for the quick reply, and I can confirm that it is resolved now!

**Comment by amir-zeldes** [comment]
Great!
