### ISSUE TITLE
Inconsistent annotation for LS entries

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/UD_English-GUMReddit#6]
1. List items are annotated with the `X` UPOS. -- EWT favours `NUM` for these and https://universaldependencies.org/u/pos/X.html states that it should be used restrictively.
2. These should have the `NumType=Ord` feature (as they specify an ordered list of items).
3. The `1.` etc variants should have the `NumForm=Digit` feature.
4. The `a)` etc variants should have a `NumForm` feature, but no suitable form currently exists for these; maybe `NumForm=Alpha` (alphabetic -- "Examples: a, b, c, α, β, γ").
5. EWT tokenizes the `(` and `)` as separate tokens.

Validation issues:
```
ERROR: Sentence GUM_reddit_bobby-9 token 48 -- invalid X form 'a)'
ERROR: Sentence GUM_reddit_bobby-9 token 75 -- invalid X form 'b)'
ERROR: Sentence GUM_reddit_racial-22 token 1 -- invalid X form '(1)'
ERROR: Sentence GUM_reddit_racial-25 token 1 -- invalid X form '(2)'
ERROR: Sentence GUM_reddit_racial-26 token 1 -- invalid X form '(3)'
```

**Comment by rhdunn** [comment]
The following list items should not have `Abbr=Yes`:
```
WARN: Sentence GUM_reddit_monsters-17 token 1 -- LS/Abbr=Yes lemma 'a.' does not have a validation rule for form 'a.'
WARN: Sentence GUM_reddit_monsters-18 token 1 -- LS/Abbr=Yes lemma 'b.' does not have a validation rule for form 'b.'
WARN: Sentence GUM_reddit_monsters-19 token 1 -- LS/Abbr=Yes lemma 'c.' does not have a validation rule for form 'c.'
```

**Comment by nschneid** [comment]
I assume this depends in part on UniversalDependencies/docs#983

**Comment by amir-zeldes** [comment]
I'm not sure these are exactly numbers. I mean, even ones that don't have letters can have structures that defy regular numbers, say "1.1.1" is not really a number of any kind. I could be convinced to put number-like features on the ones that really are numbers, like "1", but I'm not even sure if "1.1" is a number (I mean, it's definitely not trying to say the number "eleven tenths").

Will fix the Abbr part though.

**Comment by amir-zeldes** [comment]
If you want to talk more about LS being numbers, let's reopen https://github.com/UniversalDependencies/docs/issues/983. Closing this as there are no other specific GUMReddit questions here.

**Comment by rhdunn** [comment]
I'm happy with the analysis in the docs issue, with these being X+LS without number annotations.
