### ISSUE TITLE
Incorrect annotations for wrongly split RB words

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/UD_English-GUMReddit#7]
These are due to wrongly split words:
```
ERROR: Sentence GUM_reddit_pandas-38 token 22 -- RB lemma 'over' is not the lowercase form 'overpopulated' text
ERROR: Sentence GUM_reddit_escape-23 token 3 -- RB lemma 'over' is not the lowercase form 'overstep' text
ERROR: Sentence GUM_reddit_steak-9 token 16 -- RB lemma 'under' is not the lowercase form 'undercooked' text
```

According to https://universaldependencies.org/u/overview/typos.html -- and what EWT is following -- these should use:
1. Typo=Yes, CorrectForm, XPOS=GW on the first token
2. LEMMA=_, UPOS=X, XPOS=RB, DEPREL=goeswith on the second token

The first token is not using XPOS=GW, and the second token is not following any of the LEMMA, UPOS, XPOS, and DEPREL.

**Comment by amir-zeldes** [comment]
Thanks for reporting - these were actually just deprel errors, rather than processing errors. The annotation had them as compositional trees with 'over/under' as an advmod. Fixed upstream to be goeswith etc. for the next release.
